### ISSUE TITLE
Use different pin for LED examples?

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#116]
The LED recipes in http://pythonhosted.org/gpiozero/recipes/ (and also the example in http://pythonhosted.org/gpiozero/notes/ ) use GPIO 2, which is one of the I2C pins. This means that when you connect an LED to it, the weak pull-up on that pin means the LED dimly illuminates, before actually running any Python code!  (which of course may be surprising / confusing for newbies).

Maybe the LED recipes should be modified to use GPIO 17, so that they match http://pythonhosted.org/gpiozero/outputs/ ?

And / or maybe a note could be added to the Notes page about the weak pullups on GPIOs 2 & 3 ?

**Comment by waveform80** [comment]
Hmm, good point. @bennuttall any chance we can get the wiring diagram revised? Or that we could get the original SVG (so we could revise it ourselves?)

**Comment by lurch** [comment]
??
The wiring diagram (on http://pythonhosted.org/gpiozero/outputs/ ) *does* use GPIO 17, which is fine.
I was suggesting changing the recipes on http://pythonhosted.org/gpiozero/recipes/ (which don't have any pictures) to use GPIO 17 to match.

**Comment by waveform80** [comment]
Doh - I was looking the button example! Serves me right for not concentrating on things fully!

**Comment by lurch** [comment]
Looks like somebody else agrees with me ;-)
https://www.raspberrypi.org/blog/gpio-zero-a-friendly-python-api-for-physical-computing/#comment-1248535

**Comment by bennuttall** [comment]
I never replied to this - sorry. Yes, we should probably avoid the pins with nasty surprises.

@samalderhyde says the SVGs don't render correctly for some reason but he can generate all the diagrams we need. I'll give him a list when he's in a less busy period.

**Comment by waveform80** [comment]
The SVGs don't render correctly? Hmm, send 'em my way anyway; that's weird enough I'd like to the see them and they may be fixable with Inkscape (I'm betting Sam's using AI which, while a very powerful package, has rather sucky SVG handling).
