### ISSUE TITLE
Can we just install this instead of upgrading to Jessie?

### ISSUE THREAD

**Issue by hippyjim** [RPi-Distro/python-gpiozero#132]
Hi

Is there no way to just install this on Wheezy? All the "simple" instructions don't work as the package is not available. Is there a way to download it from here and install it?

**Comment by waveform80** [comment]
You can download the .debs from the [Jessie repo](http://archive.raspberrypi.org/debian/pool/main/g/gpiozero/) and `sudo dpkg -i pkgname.deb` to install it (I deliberately built the package on wheezy so it'll be compatible), or you can use `pip` with the PyPI version (`sudo pip install gpiozero`).

**Comment by waveform80** [comment]
I've just checked, and it looks like the package and all the deps (including spidev) are now in the wheezy repos too so the simple install should now work there too.
