### ISSUE TITLE
PiLiter Docs don't include PWM

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#142]

**Comment by lurch** [comment]
Looks like this has been fixed for the PiLiter http://gpiozero.readthedocs.org/en/latest/api_boards.html#piliter

But looking at the code in boards.py, I wonder if it'd make sense to also add the `pwm` parameter to the PiTraffic init method? I don't have one of these boards, so can't comment whether that'd be a suitable addition.

**Comment by waveform80** [comment]
Yeah, docs will just follow the code now (at least in the API sections anyway) so this is fixed. @bennuttall can you check if PWM works on a PiTraffic? If so, we may as well add it as an option (could re-purpose this ticket or open a new one)

**Comment by bennuttall** [comment]
Closed with
