### ISSUE TITLE
RGBLED Missing active_high param

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#143]
I've been asked about common anode RGBLEDs which work active low, and noticed that `RGBLED` doesn't have an `active_high` parameter, which would fix this.

**Comment by waveform80** [comment]
Okay, this is me showing my utter electrical ignorance again and not realizing that of course PWM devices could be wired active-low. Doh! Should have this fixed up in a bit (I'll add an active_high parameter to PWMOutputDevice, which PWMLED will inherit then add it to RGBLED too)
