### ISSUE TITLE
Bug in TrafficLightsBuzzer ?

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#164]
Is https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/boards.py#L264 missing `self.button` ? 
The dochelp for the `all` method a few lines further down mentions that the Button should be returned...

On a side-note: is it worth making `self._all` and the `all()` property a standard part of the CompositeDevice class? (and then maybe `close()` and `closed` could be handled automatically in CompositeDevice too?)
EDIT: ...and perhaps the values-get property could be handled automatically too? (from the discussion in #131 )

**Comment by lurch** [comment]
And as mentioned in https://github.com/RPi-Distro/python-gpiozero/pull/131#issuecomment-180522947 the TrafficLightsBuzzer `value` property ought to include the button's value too.

Although I dunno what 'fixing' this would mean in terms of "API breakage"? :-/

**Comment by waveform80** [comment]
This was fixed by #239 which also implements a "proper" `CompositeDevice` class (yeah, it's technically an API break but the benefit of a decent `CompositeDevice` implementation is too important to pass up - and I'm hoping this doesn't break any existing scripts :)
