### ISSUE TITLE
LEDBoard should have an active_high option

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#175]
So that it can be used with both common-cathode and common-anode configurations of groups of LEDs.

**Comment by lurch** [comment]
In fact I guess this should be added in LEDCollection.

**Comment by lurch** [comment]
Hmm, the way you've done it there is to assign the identical `initial_value` to every LED in the LEDBoard. The way I was imagining it working, was to have the (optional) `iniital_value` be a tuple, with an exception thrown if it's a different size to the `pins` tuple, and then using the initial_value tuple-values to initialise the individual LEDClass initial-values (maybe by using something like `enumerate` or `zip`).

**Comment by bennuttall** [comment]
You could do, but that's a complex init for an odd case, I'd say. Probably easier just to set them up after init. What do you think, @waveform80?

**Comment by lurch** [comment]
https://github.com/RPi-Distro/python-gpiozero/pull/176#issuecomment-181906439
