### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by waveform80** [RPi-Distro/python-gpiozero#179]
Because ... tests!

This is overdue, but now that the pins work is merged it's actually substantially easier. We should be able to construct a MockPin class and use that for testing all the device stuff. As for testing the pin implementations themselves, I'll come up with some minimal hardware config for it but it's probably not hard (wire one GPIO to another, configure one as output, one as input, test away - or something like that).

**Comment by bennuttall** [comment]
I wanted tests before it was cool. #87

**Comment by waveform80** [comment]
Doh! Closing as duplicate of #87 because Dave didn't search the issues first :(

**Comment by bennuttall** [comment]
:)
