### ISSUE TITLE
LEDBarGraph PWM support

### ISSUE THREAD

**Issue by waveform80** [RPi-Distro/python-gpiozero#182]
As mentioned in comments in #176 there's several things to clean up:

* [x] Add PWM support to LEDBarGraph
* [x] Document LEDCollection in generic API docs (don't forget the hierarchy diagram)
* [x] Add pot->graph recipe to Recipes chapter
* [x] Fix the description of the first example in the docs

**Comment by bennuttall** [comment]
What's your plan for PWM support? A value of 0.5 for 3 LEDs = `[1, 0.5, 0]`?

**Comment by waveform80** [comment]
Yeah, that's basically the idea - every LED is either on (value > LED's threshold), off (value < prior LED's threshold) or on a PWM duty-cycle linearly proportional to how far value sits between the current and prior LED's thresholds.

**Comment by bennuttall** [comment]
Cool. I might have a go.

**Comment by waveform80** [comment]
Go for it :)

**Comment by bennuttall** [comment]
Ok got distracted. I'm sure I can tackle this - not now though.
