### ISSUE TITLE
pin_layout needs updating for Pi3

### ISSUE THREAD

**Issue by DeeJay** [RPi-Distro/python-gpiozero#231]
The pin layout diagrams at .../docs/images/pin_layout.* need updating for Pi3. (As I understand it, there is no change to pin usage, but the legend at the bottom needs changing for clarity.)

**Comment by lurch** [comment]
The PiZero uses the same layout too. Maybe it just ought to be categorised as something like "26-pin Pis" and "40-pin Pis" ?

**Comment by waveform80** [comment]
Yeah, I was thinking something similar (either that or the fact that there's now more models that support 40 than 26 that it's almost worth writing "not A/1B" instead of "0/A+/B+/2B/3B" on the bottom). I'll have a play with it later this evening.
