### ISSUE TITLE
when_held missing from documentation

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#287]
I was just looking up the usage of `button.when_held` but found it wasn't listed under `Button`. I inspected the source and realised that's because it comes from `HoldableMixin` and the docs don't automatically show parent class members.

Is it possible to show the hold stuff for `Button` in the docs, and/or (probably and) can we add a recipe for it?

@waveform80 @martinohanlon

**Comment by waveform80** [comment]
Argh - that's my fault - I'll bung it in the API (I can set the docs to just include everything from parent classes, but the parent API is now pretty bulky what with `source`, `source_delay`, `values`, etc. so for the "simpler" concrete classes like `Button` we tend to [explicitly list what gets shown](https://raw.githubusercontent.com/RPi-Distro/python-gpiozero/master/docs/api_input.rst)).

**Comment by waveform80** [comment]
Bah, beat me to it ... need more hours in my day!

**Comment by bennuttall** [comment]
Trying to do what I can! Do you think I missed anything or added anything I shouldn't?

**Comment by waveform80** [comment]
No, looks fine to me. If you want to test docs before committing / pushing / merging / whatever, just run "make doc" and then look at `docs/_build/html/` for the results (`docs/_build/latex` will have the PDF output).

**Comment by lurch** [comment]
...but bear in mind that you'll need to do `sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended` before being able to do `make doc`.

**Comment by waveform80** [comment]
oh good point - I should add that stuff to the developer docs in picamera!
