### ISSUE TITLE
Robot Recipes inconsistency

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#288]
While looking through the Recipes page, I just noticed that some of them use `Robot` while others use `RyanteckRobot`.

Should they all use the base Robot class? Or should one of them be modified to illustrate using the CamJamKitRobot class too?

**Comment by waveform80** [comment]
Huh, good point. I'm tempted to make them all `Robot` and add some links to the common board types being available to the prose. Any thoughts @bennuttall?

**Comment by bennuttall** [comment]
No reason other than demonstrating use of the pre-defined version. It doesn't make a huge difference but using `Robot` is probably more generic.
