### ISSUE TITLE
Add note about remote access

### ISSUE THREAD

**Issue by IanHun** [RPi-Distro/python-gpiozero#289]
Note

The second example of the Keyboard Controlled Robot will only work if the keyboard/screen are attached directly to the RPi, so will not work with remote access mechanisms (SSH and VNC).

**Comment by waveform80** [comment]
Interesting - can't say I've tried evdev over SSH. I presume there must be some workaround (otherwise how would X get evdev events from a forwarded session over SSH), but I'm not sure it'll be trivial enough for the recipe. Either way, we should either document the short-coming or fix it.

**Comment by lurch** [comment]
> I presume there must be some workaround (otherwise how would X get evdev events from a forwarded session over SSH)

Perhaps that's one of the intricacies of using `ssh -X ...` rather than just a plain 'console' ssh session? \*shrug\*
But I guess evdev also won't work over a serial console, whereas ncurses would.

**Comment by waveform80** [comment]
Okay, so there aren't evdev messages going over SSH - it's straight X messages (which makes sense now I think about it) so this recipe will never work over SSH. I'll add a note to the docs to that effect. Incidentally, while digging into this I also found out how to detect a keyboard from evdev, so I'll enhance the recipe a little to include that (as my keyboard doesn't show up as device[0] typically and it'd be nice to have it "Just Work").
