### ISSUE TITLE
internal device idea: cpu temperature

### ISSUE THREAD

**Issue by drewp** [RPi-Distro/python-gpiozero#294]
You might like to offer /sys/class/thermal/thermal_zone0/temp (divide by 1000 for C) as one of the internal devices on https://gpiozero.readthedocs.org/en/v1.2.0/api_other.html

**Comment by lurch** [comment]
Nice idea. Should probably have the same API as #93

**Comment by bennuttall** [comment]
http://www.stuffaboutcode.com/2015/06/raspberry-pi-cpu-temperature.html @martinohanlon

**Comment by martinohanlon** [comment]
I like the idea of creating a CPU class where you could gain information about the CPU - temperature, version, clock speed, serial no, overclocking etc.

Should this form part of gpio-zero though? It feels outside the scope of the module.

Do we need a new module? A raspberry_pi module which provides access to classes relating to the computer. CPU, GPU, Audio, Display, USB, Bluetooth, Wifi, RAM, Storage, etc.

**Comment by lurch** [comment]
> Should this form part of gpio-zero though? It feels outside the scope of the module.

That's what I wondered too, but @waveform80 already added most of what you listed to http://gpiozero.readthedocs.org/en/latest/api_pins.html#utilities

**Comment by waveform80** [comment]
I do like the idea of an internal temperature device - that's exactly the sort of thing the internal devices are for (not representable on the GPIO pins, but specific to the Pi, and useful as a data-source for pin-controlled devices).

**Comment by waveform80** [comment]
The data module (and associated pi_info function) does indeed add most of the stuff @martinohanlon lists above - but not all. The stuff included is specifically: fixed information (not temperature, which should be handled by a device as it's dynamic) and secondly difficult to get elsewhere (I don't include the number of CPU cores because you can get it trivially from /proc/cpuinfo, but memory isn't as trivial because of the CPU/GPU mem split so it is included, number of built-in USB ports is likewise difficult to calculate, and so on).

**Comment by bennuttall** [comment]
I like the idea

**Comment by bennuttall** [comment]
Especially with values!

**Comment by dglaude** [comment]
As an advocate of remotely controling GPIO accross pigpio protocol, would prefer not to add to gpiozero stuff that are not related to GPIO and not reachable via pigpio protocol.

**Comment by lurch** [comment]
I dunno - I'm not sure we should restrict gpiozero to only offering features that can be controlled over a remote pigpiod connection :-/
I'm fairly sure the overwhelming majority of gpiozero users will be running it on-Pi and not over a remote network connection.

**Comment by waveform80** [comment]
Yup, still all for this. I don't see lack of pigpio support as a show-stopper; there's no reason an interface for this couldn't be added to pigpio later if it became a popular request and as @lurch notes the vast majority of gpiozero use is local. Might have a crack at this later tonight (unfortunately I've got to go play recklessly with fire on the BBQ the rest of this afternoon!)
