### ISSUE TITLE
Alias "amber" to "yellow" for American users

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#345]
When teaching with gpiozero at Picademy USA, I discovered that they commonly refer to the middle light as "yellow", rather than "amber".

I suggest we add an alias for this.

@mrichardson23

**Comment by lurch** [comment]
And interestingly, all the "traffic lights" boards which gpiozero supports actually have yellow LEDs ;-)
https://en.wikipedia.org/wiki/Traffic_light mentions both amber and yellow.

**Comment by bennuttall** [comment]
@mrichardson23 FYI this is now released
