### ISSUE TITLE
Problem with images on RTD documentation

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#364]
I'm not sure how it's gone wrong, or what needs to be done to get it back in sync, but for some reason http://gpiozero.readthedocs.io/en/stable/_images/composed_devices.svg (as displayed on http://gpiozero.readthedocs.io/en/stable/api_boards.html#base-classes) is lagging behind https://github.com/RPi-Distro/python-gpiozero/blob/master/docs/images/composed_devices.svg

**Comment by waveform80** [comment]
You're looking at gpiozero.readthedocs.io/en/stable - which isn't "latest". I'm not sure exactly how RTD defines "stable" ... I think it's the last named version prior to master, in which case looking at "stable" is equivalent to looking at "1.2.0" which won't include that updated graph. If you look at "latest" it is indeed up to date.

**Comment by lurch** [comment]
Doh! My mistake, sorry.
