### ISSUE TITLE
ComputeModule USB ports

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#384]
I've just been looking at https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/pins/data.py#L244

If the ComputeModule is listed as having 2 CSI ports and 2 DSI ports, then surely it should also be listed as having 1 USB port?
(Happy to fix this myself if I get the nod from @bennuttall or @waveform80 )

**Comment by waveform80** [comment]
Ooops - good point. Must've missed the (blindingly obvious) USB pins on the SODIMM list :)

**Comment by 6by9** [comment]
There is a comment at https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/pins/data.py#L392
>             On the Compute Module this is listed as 0 as the compute module
            itself doesn't have any physical USB headers, despite providing one
            on the I/O development board and having the pins for one on the
            module itself.

That's no longer true.

**Comment by lurch** [comment]
Ah, well spotted @6by9 !
#405 ... ;-)

**Comment by waveform80** [comment]
Ahh that explains it - I didn't miss the pins, I just made the bizarre choice to count the CSI pins and not the USB ones. Well, let's get this all nice and consistent now...
