### ISSUE TITLE
Change default pin factory to pigpio

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#424]
Should we change the default pin factory from RPi.GPIO to pigpio in the upcoming v1.4 release?

Update: let's try for v1.5 :)

**Comment by lurch** [comment]
https://github.com/RPi-Distro/python-gpiozero/issues/248#issuecomment-205959582

https://github.com/RPi-Distro/python-gpiozero/issues/248#issuecomment-219285355

And IMHO we'd need much more comprehensive unit-tests before switching the default Pin backend.

**Comment by waveform80** [comment]
Indeed - also, now that backend can be switched with nothing more than an environment variable (which people could set in .bashrc if they want to use a particular backend all the time), there's less reason to move the default until we've got comprehensive tests.

**Comment by lurch** [comment]
> now that backend can be switched with nothing more than an environment variable

Unfortunately that's not been [documented](http://gpiozero.readthedocs.io/en/v1.3.1/api_pins.html) yet :-/

**Comment by waveform80** [comment]
Doh - definitely ought to have that in there somewhere ... maybe the pins chapter header. Maybe link to that from the Servo docs.

**Comment by bennuttall** [comment]
Probably not the best idea as it requires pigpiod to be running.
