### ISSUE TITLE
Deb packaging

### ISSUE THREAD

**Issue by waveform80** [RPi-Distro/python-gpiozero#44]
We should get on with Raspbian packaging fairly quickly. I want this on the image for the next Birmingham picademy, and I'd like to include instructions on the worksheet for teachers to install this on any other Pi's they have with minimal hassle. I can handle this if you wish.

**Comment by bennuttall** [comment]
Yes please - go ahead

**Comment by waveform80** [comment]
Argh ... spidev and w1thermsensor aren't packaged for Raspbian. I'll have to make those local imports and come up with some "friendly" error telling the user how to install them in the event they're not present

**Comment by waveform80** [comment]
(or package them myself, but I really don't have the time to devote to that)

**Comment by bennuttall** [comment]
Hmm. Maybe we should look at packaging them. I'll ask when I'm back in the office.

**Comment by timofurrer** [comment]
@bennuttall Is this the issue why you need the w1thermsensor module as package in the repos?
I'll definitely gonna work on it ...

**Comment by bennuttall** [comment]
Yes - thanks!

**Comment by waveform80** [comment]
Quick question before I redo the PR for deb packaging - I'm assuming the w1thermsensor package is going to be packaged as python-w1thermsensor and python3-w1thermsensor, and that spidev will be packaged as python-spidev and python3-spidev in accordance with the usual Debian convention? Just need to check for the deps in the control file

**Comment by bennuttall** [comment]
I would think so. @XECDesign?

**Comment by XECDesign** [comment]
Yeah, that's right.

**Comment by timofurrer** [comment]
Yes - for w1thermsensor the same ..

**Comment by waveform80** [comment]
Good stuff - I'll bung in the PR in a bit

**Comment by bennuttall** [comment]
Reopening until the package is released!

**Comment by waveform80** [comment]
Heh - good point :)

**Comment by timofurrer** [comment]
Use the following commands to create the python 2 and python 3 packages:

For python 2:
```bash 
python setup.py --command-packages=stdeb.command bdist_deb
```

For python 3:
```bash
python3 setup.py --command-packages=stdeb.command bdist_deb
```

Do you need something else in order to include it to the repositories?

**Comment by waveform80** [comment]
The machinery for making the deb package should all be in there after PR #54, we're just fixing a few other things before the next release at the moment. The machinery is based on stdeb's output but with a few tweaks that I've built up over the years to make certain things easier (most of it's in the Makefile and handles things like launching dch to update the changelog properly and in the fuller versions that I use on picamera and picraft, building the separate docs package automatically, integrating it with docs-base, and auto-uploading everything to PyPI and the Raspbian maintainer via dput)

**Comment by bennuttall** [comment]
I didn't use this for the 0.9 release as I needed to get it out - but will try by the next release.

**Comment by waveform80** [comment]
No prob - let me know if you have any issues. I can always run it if you like as I'm set up for signing packages and Serge's got my public keys on the Raspbian dput servers (which is why I can automate the whole thing from package building to uploading to PyPI and Raspbian)

**Comment by lurch** [comment]
Will the python-w1thermsensor, python3-w1thermsensor, python-spidev and python3-spidev packages also be added to the Wheezy repositories? Or will they remain Jessie-only?

**Comment by waveform80** [comment]
That would be the "proper" solution here (and I suspect the easiest though
I'm not au fait with the particulars); I haven't heard the verdict on that
yet though.

**Comment by bennuttall** [comment]
That would make things a lot easier. We do want people to upgrade to Jessie, but I don't like the idea of this just not working in Wheezy. It's possible to supply separate instructions for Wheezy but that gets complicated. 

@XECDesign do you think we could make Wheezy packages for this and its dependencies?

**Comment by XECDesign** [comment]
If someone can confirm that they 'just work' as they are, I don't see why not.

**Comment by bennuttall** [comment]
They should! Send me some debs and I'll test them. Thanks

**Comment by XECDesign** [comment]
http://archive.raspberrypi.org/debian/pool/main/w/w1thermsensor/python-w1thermsensor_0.2.2-1_all.deb
http://archive.raspberrypi.org/debian/pool/main/w/w1thermsensor/python3-w1thermsensor_0.2.2-1_all.deb
http://archive.raspberrypi.org/debian/pool/main/s/spidev/python-spidev_2.0~git20150907_armhf.deb
http://archive.raspberrypi.org/debian/pool/main/s/spidev/python3-spidev_2.0~git20150907_armhf.deb

**Comment by waveform80** [comment]
Right, packaging is tested and works nicely (on jessie - it'll work on wheezy as well when/if the spidev packages are back-ported there) so I'll close this for release
