### ISSUE TITLE
Include LICENCE.txt in packages?

### ISSUE THREAD

**Issue by lurch** [RPi-Distro/python-gpiozero#456]
I'm not familiar at all with Python packaging, but should `MANIFEST.in` include:

```
include LICENCE.txt
```

?

**Comment by waveform80** [comment]
Erm ... good question. "Probably" is my answer, but I'd have to check what that does with the deb packaging (which partially depends on the python packaging)

**Comment by thijstriemstra** [comment]
why not?

**Comment by mirabilos** [comment]
@waveform80 the Debian packaging ships its own `debian/copyright` file in the Debian source package, which ends up in `/usr/share/doc/*/copyright` in the Debian binary package, and will omit the `LICENCE.txt` file completely, but its presence in the `.orig.tar.gz` file is still required by the licence itself.

**Comment by lurch** [comment]
Fixed as part of #535
