### ISSUE TITLE
Re-title header on B+ onwards

### ISSUE THREAD

**Issue by waveform80** [RPi-Distro/python-gpiozero#461]
Just realized (whilst in the middle of the pins re-factor, mulling over exactly how to handle inter-device pin locking) that the header on the B+ onwards _isn't_ P1 ... it's J8. I'll get this fixed up while I'm at it to avoid any confusion of users looking at their Pi's and going "but where the hell is P1?!"

**Comment by lurch** [comment]
...but it's labelled as "GPIO".

**Comment by waveform80** [comment]
look at the bit just by pin 1

**Comment by waveform80** [comment]
had a look on a Zero, a 2B, and a 3B (haven't got a B+ but I've found some photos online) - I'm pretty sure that header is labelled J8 but you're right there's a "GPIO" label silk-screened on too.

**Comment by lurch** [comment]
Ah yes. They even kept the "J8" labelling on the PiZero, which is surprising.

**Comment by lurch** [comment]
BTW I had already noticed this (P1 discrepancy), but I didn't think it was worth fixing ;-)

**Comment by waveform80** [comment]
Somehow the fact you'd already noticed it doesn't surprise me ;)

**Comment by bennuttall** [comment]
What do P1 and J8 stand for?

**Comment by lurch** [comment]
@bennuttall I think this has been done, as the pinout diagrams now include 'J8' ?

**Comment by bennuttall** [comment]
:+1:
