### ISSUE TITLE
Common problems docs

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#474]
Perhaps we could create a page in the docs which covers common problems with gpiozero?

Suggestions:
- ImportError: No module named 'gpiozero'
- Callback not working (#136)

Others?

**Comment by waveform80** [comment]
Should I just turn Notes into a FAQ? (it's basically structured like that already - might as well make it official?)

**Comment by bennuttall** [comment]
That might make sense
