### ISSUE TITLE
Cannot create AngularServo with initial_angle=None

### ISSUE THREAD

**Issue by thagrol** [RPi-Distro/python-gpiozero#476]
Attempting to run the following code snippet results in a TypeError exception.

`import gpiozero`
`s=gpiozero.AngularServo(21,initial_angle=None)`

Traceback:
`Traceback (most recent call last):`
`File "<pyshell#33>", line 1, in <module>`
`s=gpiozero.AngularServo(21,initial_angle=None)`
`File "/usr/lib/python2.7/dist-packages/gpiozero/devices.py", line 135, in __call__`
`self = super(GPIOMeta, cls).__call__(*args, **kwargs)`
`File "/usr/lib/python2.7/dist-packages/gpiozero/output_devices.py", line 1157, in __init__`
`initial_value = 2 * ((initial_angle - min_angle) / self._angular_range) - 1`
`TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'`

While unclear, the documentation suggests that this should be possible in order to start the servo uncontrolled. Exception does not occur if "initial_angle" is omitted or set to a suitable numeric value. "Pin" value appears to have no effect on this either.

**Comment by lurch** [comment]
Fixed by #491
