### ISSUE TITLE
Fall back to MockPin over Native Pin for non-Pi users

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#513]
If I have gpiozero on a Pi the existing pin factory priority makes sense:

1. RPi.GPIO
2. RPIO
3. pigpio
4. Native Pin

(i.e. if they have no pins library installed, native pin kicks in and their hardware still works)

However, if I'm on a PC and am running gpiozero, falling back to Native Pin is pointless. It would be better to simply look for pigpio, and fall back to MockPin (or probably MockPWMPin to be safe).

Would it be possible to have different priorities according to whether or not you're on a Pi? If so, do you agree, @waveform80 @lurch?

**Comment by lurch** [comment]
I'm guessing this didn't get implemented? When I try this on my Ubuntu PC:
```python
>>> from gpiozero import LED
>>> led = LED(4)
```
I get an error that `gpiozero.exc.BadPinFactory: Unable to load any default pin factory!`
