### ISSUE TITLE
Motor & Robot method names

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#52]
Should the motor and robot interfaces be `forward()` and `backward()` or `forwards()` and `backwards()`?

**Comment by waveform80** [comment]
My rule of thumb for APIs generally: code is in American English so choose whichever is more American. If both are acceptable then flip a coin or don't bother altering it.

Quick bit of research: "forwards" seems to be acceptable in American but [less common](http://english.stackexchange.com/questions/109924/is-it-backward-forward-or-backwards-forwards) than "forward" so I'd stick with the current forward and backward.

**Comment by bennuttall** [comment]
Ok let's leave it - thanks
