### ISSUE TITLE
Do not error for unknown Pi revisions

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#529]
We can't have gpiozero not work on new Pi models, new manufacturers or other unknown information. We need to ensure that when `pi_info` is unable to parse the revision, it deals with it properly, rather than erroring immediately.

I think this can mostly be done by using `.get()` lookups on dicts with default values set.

Re: #527

**Comment by lurch** [comment]
I guess it could simply display 'Unknown' for any fields in the revision-code that it wasn't able to parse?

**Comment by joan2937** [comment]
Will you also have the problem a bit lower down with RPi.GPIO and RPIO.GPIO?

I think pigpio will ignore the issue and assume the board has the standard 40 pin expansion header.
