### ISSUE TITLE
Reinstate CONTRIBUTING.md

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#544]
I just thought about adding a note to our contributing policy to advise users to check for duplicate issues before posting a new issue, but realised it's no longer there, as it was moved into the docs directory in 335ccdfb6020833fa843fc8fcd3de370a5e0e5b6.

On the new issue page, GitHub shows a link to your contributing policy if you have a `CONTRIBUTING.md` file in your project root (or, I think, in `.github`). So we should reintroduce it at some point. It may require duplciation of what's in `docs`.

**Comment by lurch** [comment]
Agreed. Previously discussed at https://github.com/RPi-Distro/python-gpiozero/pull/403#issuecomment-240036677
