### ISSUE TITLE
ImportError: cannot import name Servo

### ISSUE THREAD

**Issue by Darth-Carrotpie** [RPi-Distro/python-gpiozero#554]
code:
```python
from tkinter import *
from gpiozero import Servo
```

error:

```
sudo python3 hit.py
Traceback (most recent call last):
  File "hit.py", line 2, in <module>
    from gpiozero import Servo
ImportError: cannot import name Servo
```

--
afterwards tried importing Motor, LED classes,  - they work fine.
Servo , AngularServo - do not.

**Comment by bennuttall** [comment]
Perhaps you have an old version of gpiozero? The latest version is 1.3.2 and Servo only landed in 1.3.0. You can check what version you have installed by following the steps documented here: http://gpiozero.readthedocs.io/en/stable/notes.html#how-can-i-tell-what-version-of-gpiozero-i-have-installed
