### ISSUE TITLE
Different reading in MCP3008 using hardware vs. software SpiDev

### ISSUE THREAD

**Issue by droscy** [RPi-Distro/python-gpiozero#555]
Hello, I've noticed that values read by MCP3008 objects are different if using hardware or software SpiDev implementation.

This is my testing script
```python
#!/usr/bin/python3
from gpiozero import MCP3008
from gpiozero.spi import extract_spi_args, SharedSPIHardwareInterface, \
    SharedSPISoftwareInterface

spi_args, kwargs = extract_spi_args()
hardware_spi_args = {'port': 0,
                     'device': {8: 0, 7: 1}[spi_args['select_pin']]}

adc = MCP3008(channel=0)

# my vref on the A/D converter
vref = (3.32/(3.32+7.5))*3.3*1000

# hardware test
adc._spi = SharedSPIHardwareInterface(**hardware_spi_args)
hw = adc.value * vref
print('hw: {:.2f}mV ==> {:.2f}°C'.format(hw, (hw-500)/10))

# software test
adc._spi = SharedSPISoftwareInterface(**spi_args)
sw = adc.value * vref
print('sw: {:.2f}mV ==> {:.2f}°C'.format(sw, (sw-500)/10))
```

and this is the result
```
hw: 691.87mV ==> 19.19°C
sw: 721.57mV ==> 22.16°C
```
with MCP3008 connected to a TMP36 thermometer.

My system is a Raspberry Pi Zero with Raspbian stretch. Tested with gpiozero 1.3.2 or just cloned and spidev 2.0 or 3.3 just cloned.

**Comment by fivdi** [comment]
This is likely to be related to the electrical characteristics of the MCP3008 and the TMP36 combined with the SPI clock speed. The analog input sampling time for the MCP3008 is 1.5 clock cycles (see page 3 of the [MCP3008 datasheet](https://cdn-shop.adafruit.com/datasheets/MCP3008.pdf)), so changing the SPI clock speed changes the sampling time. If the analog output of a TMP36 is connected directly to an analog input of the MCP3008 without any additional circuitry the temperature readings will vary depending on the SPI clock speed.

I haven't verified it but would imagine that software SPI is slower than hardware SPI which results in software SPI running at a lower clock speed than hardware SPI. The different SPI clock speeds are leading to the different temperature readings.

I saw similar effects while implementing [mcp-spi-adc](https://github.com/fivdi/mcp-spi-adc).
