### ISSUE TITLE
gpiozero and Python 3.6

### ISSUE THREAD

**Issue by rcopelan-business** [RPi-Distro/python-gpiozero#562]
I compiled Python 3.6.1 on raspbian 2017-01-11.   When trying to import the gpiozero module and get  "ModuleNotFoundError".    Did   apt-get remove python3-gpiozero and   apt-get install python3-gpio but the error message is unaffected.   I'm sure that the problem has something to do that I compiled that version  and not just apt-get install but not sure where to look for a solution.     Any pointers will be appreciate.

**Comment by bennuttall** [comment]
Have you tried installing it with pip?

```
sudo pip3 install gpiozero
```

**Comment by rcopelan-business** [comment]
that fixed it Ben.  Thanks very much.
