### ISSUE TITLE
Should LED extend PWMOutputDevice instead of DigitalOutputDevice?

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#58]
Making LED a PWM device by default would enable a brightness setting (if we aliased `.value` as `.brightness`):

```python
>>> led = LED(2)
>>> led.on()
>>> led.off()
>>> led.brightness = 0.5
```

Any reason not to? The alternative is leave it as it is, and people can manually create the led as a `PWMOutputDevice` object.

We would need to ensure #57 is fixed first.

**Comment by bennuttall** [comment]
#57 is fixed

**Comment by bennuttall** [comment]
@waveform80 what's the decision?

`LED` extends `PWMOutputDevice` or `LED` stays and we introduce `PWMLED`?

I think we said the latter.

**Comment by waveform80** [comment]
Latter sounds good to me - I'm actually fine either way, but I have a tiny preference for having something brutally simple for LED (I'm just a nervous about RPi.GPIO's PWM implementation)

**Comment by bennuttall** [comment]
Ok sure - I'll throw it in now.
