### ISSUE TITLE
gpiozero command works properly in Thonny but not when run directly from command line

### ISSUE THREAD

**Issue by iseldonz** [RPi-Distro/python-gpiozero#594]
Using THONNY (because I am a Python newbie), scripts containing either of these gpiozero commands work as  they should:

----

```python
#!/usr/bin/python3
from gpiozero import OutputDevice

FMPwr = OutputDevice(4, active_high=False, initial_value=True)
FMPwr.on()
```

----

```python
#!/usr/bin/python3
from gpiozero import OutputDevice

FMPwr = OutputDevice(4, active_high=False, initial_value=False)
FMPwr.off()
```

----

But when run from the command line the same script containing FMPwr.on
does NOT work, while the one containing FMPwr.off works properly.

Scripts containing the following (i.e. not using gpiozero) work properly in both environments:

----

```python
#!/usr/bin/python3

import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(4, GPIO.OUT)
GPIO.output(4,GPIO.LOW)
```

----

```python
#!/usr/bin/python3

import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(4, GPIO.OUT)
GPIO.output(4,GPIO.HIGH)
```

**Comment by bennuttall** [comment]
This is to be expected. Please observe the first note in the FAQs: http://gpiozero.readthedocs.io/en/stable/faq.html#how-do-i-keep-my-script-running
