### ISSUE TITLE
gpiozero is not reading GPIO inputs

### ISSUE THREAD

**Issue by larsks** [RPi-Distro/python-gpiozero#597]
On my raspberry pi 3 (running "Raspbian GNU/Linux 9 (stretch)"), with Python 3.5.3, the [Button controlled LED](https://gpiozero.readthedocs.io/en/stable/recipes.html#button-controlled-led) example doesn't work (the LED never lights).  Taking a closer look, it appears that `gpiozero` simply isn't reading the value of the GPIO pins at all.

The problem appears to b exclusive to `gpiozero`; using `RPi.GPIO` directly doesn't exhibit this problem.  For example, if I wire pin 23 straight to +3.3v, then using `gpiozero` I see:

```python
>>> import gpiozero
>>> button = gpiozero.Button(23)
>>> button.value
False
```
But using `RPi.GPIO` I see:

```python
>>> import RPi.GPIO as GPIO
>>> GPIO.setmode(GPIO.BCM)
>>> GPIO.setup(23, GPIO.IN)
>>> GPIO.input(23)
1
```

Outputs seem to work just fine; if I run:

```python
>>> import gpiozero
>>> led = gpiozero.LED(15)
>>> led.on()

```
...then the attached LED lights as expected.

**Comment by bennuttall** [comment]
In RPI.GPIO the default pull-up state for an input pin is "off", whereas in gpiozero the default pull-up state is "up".

Pull-up button:

```python
GPIO.input(23, GPIO.IN, GPIO.PUD_UP)
```

```python
Button(23, pull_up=True)
```

Pull-down button:

```python
GPIO.input(23, GPIO.IN, GPIO.PUD_DOWN)
```

```python
Button(23, pull_up=False)
```

Does that explain the discrepancy?
