### ISSUE TITLE
Initial delay before running script

### ISSUE THREAD

**Issue by RokCernelic** [RPi-Distro/python-gpiozero#599]
Hello,
I'm trying to run some example scripts as desribed in GPIOZERO documentation. Is it normal to have a quite long (few sec) initial delay when executing a python script with some example code (for Motion Sensor, Distance Sensor ...)?

**Comment by bennuttall** [comment]
Yes - there's a lot of setup required, working out which pin factory to load, and that kind of thing, I'm afraid.
