### ISSUE TITLE
pigpio site is changing from abyz.co.uk to abyz.me.uk

### ISSUE THREAD

**Issue by joan2937** [RPi-Distro/python-gpiozero#603]
Sorry for this abuse of your issue system and the extremely late notification.

I did consider going through the documents, finding references, forking then raising a pull request for each one.  However I have no idea how many links there might be (apart from at least two in remote gpio).

As the title says any link or reference to abyz.co.uk should now be abyz.me.uk.

**Comment by bennuttall** [comment]
Thanks for letting us know. Are you maintaining the redirection?

I'll push a global replacement later.

**Comment by joan2937** [comment]
Thanks.

abyz.co.uk should redirect for another year then I'll be releasing the domain.
