### ISSUE TITLE
/var/log filled sd card after using remote gpio library

### ISSUE THREAD

**Issue by av4625** [RPi-Distro/python-gpiozero#612]
I wrote this script (I may be using it wrong)

<img width="331" alt="screen shot 2017-12-03 at 00 39 02" src="https://user-images.githubusercontent.com/19472253/33521167-727a83de-d7c2-11e7-8150-2c6babd22eb2.png">

But it has seemed to fill my sd card with massive logs in /var/log
daemon.log and syslog and syslog.1 are huge and contain the following line:
python3[1793]: ALSA lib pcm.c:7843:(snd_pcm_recover) overrun occurred

**Comment by lurch** [comment]
Why was this closed? ;)
What version of GpioZero are you using? What version of Raspbian are you using?

**Comment by av4625** [comment]
This was the only thing I had done on the raspberry pi recently so thought it was the issue.
I also have google aiy on the raspberry pi and I think it may be the issue as it just randomly stopped working and I cant get it to work again.
Gpiozero 1.4.0 and Jessie

**Comment by lurch** [comment]
I don't know, that's not a combination I've tried myself. If you can recreate this problem on a freshly-written SD card then please re-open this issue.

**Comment by av4625** [comment]
I just got this again with a freshly written SD card, daemon.log and syslog got filled agin.

This time it uses the newer version of google aiy which is different than the old version.

This is everything that is installed.
MySQL
sudo apt-get install mysql-server --fix-missing
sudo apt-get install mysql-client php5-mysql

Connect to MySQL from python
sudo apt-get install python-dev libmysqlclient-dev
sudo apt-get install python-mysqldb
pip install mysqlclient

Vim
sudo apt-get install vim

Apache
sudo apt-get install apache2

PHP
sudo apt-get install php5cd /var

The remote daemon is also on

**Comment by lurch** [comment]
Hmmm, then perhaps there's some kind of conflict with google AIY and pigpiod? (pigpiod is the underlying library that GpioZero uses for remote gpio)

Might be worth chasing up this bug on each of those projects' websites.
https://aiyprojects.withgoogle.com/
http://abyz.me.uk/rpi/pigpio/pigpiod.html

(ping @joan2937 )

**Comment by bennuttall** [comment]
Yeah this isn't a bug in gpiozero, it's something going on with pigpio.

**Comment by joan2937** [comment]
The logs are apparently being created by the ALSA library.  By default pigpio uses the PCM peripheral to time the GPIO sampling.  Presumably Google AIY is also using the PCM peripheral via the ALSA library.

One way to test would be to start the pigpio daemon with the **-t0** option (see http://abyz.me.uk/rpi/pigpio/pigpiod.html).  pigpiod will then use the PWM peripheral instead of the PCM peripheral. 

E.g. try something like the following.

```
sudo killall pigpiod
sudo pigpiod -t0
```

**Comment by lurch** [comment]
@joan2937 Oooh, interesting. As somebody who knows very little about all this, does using PCM over PWM (or vice versa) allow more precision in pigpiod, or are they both equally capable?
Would there be a possibility to also have an additional `-t 2` clock option, to then have pigpiod use **No** clock peripheral? (with errors then thrown as appropriate if the user tries to use a function which requires a clock peripheral)   Or perhaps that's a stupid question? ;-)

**Comment by joan2937** [comment]
@lurch 

PWM and PCM are equal as far as the timing is concerned.

They are actually used to pace the DMA transfers (an idea of Gerts, first implemented by Richard Hirst and used in his servoblaster).  The GPIO are sampled by a DMA transfer from the GPIO register to memory.

High speed sampling and accurate time-stamping are central to pigpio.  They are the reason it exists.  This would be impossible without using DMA transfers.  As a byproduct you also get pretty accurate PWM generation on all the GPIO for free.

**Comment by av4625** [comment]
Thanks guys for all your help, (sorry for posting the issue in the wrong place, I was confused at first when it happened)

I have tried joan's suggestion and it seems to work so far.
It throws this error:
/home/pi/AIY-voice-kit-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.

This is the led for the button but the led seems to work

**Comment by lurch** [comment]
@joan2937 As far as GpioZero is concerned, the remote-connection feature is pigpio's killer feature ;-)
I don't think GpioZero actually makes use of High speed sampling and accurate time-stamping (although I'm sure other people must find them useful) - GpioZero kinda adopts a lowest-common-denominator approach, so that different GPIO libraries can be swapped in and out.

@av4625 Glad to hear that things are working now :-)

**Comment by joan2937** [comment]
@lurch 

One thing I would do, time permitting, is copy the source base and make a new project.  I'd then strip out all the DMA sampling, waves, PWM.  That would leave generic code which should work on any Linux platform.  There would still be a lot of functionality left.  Sampling and PWM could be added back in albeit in a degraded pure software form.
