### ISSUE TITLE
SmoothedInputDevice (wrongly?) uses the Median (instead of the Average) on the queue to return the value

### ISSUE THREAD

**Issue by holzfigure** [RPi-Distro/python-gpiozero#615]
While in the documentation it says that the *mean* or *average* of the values in the internal queue will be compared to `threshold` to determine whether device `is_active`, `.value` in fact returns the **median** of the queue. I fixed it for myself in `mixins.py`, by importing the `mean` and then passing it as the default `average` keyword parameter to the `__init__()`-function of `GPIOQueue()`.

I wonder whether taking the median serves a purpose i'm unaware of (apart from contradicting the documentation, hehe), but given digital inputs, the median can only return 0 or 1 (or very rarely 0.5), strongly reducing the functionality of the `threshold`.

I suggest changing that behavior to using the **arithmetic mean** instead of the median?

**Comment by lurch** [comment]
Oh, well spotted! #615 should (hopefully) fix this - if you can test it that'd be great.

**Comment by holzfigure** [comment]
just tested it, works fine. It's actually easy to test: just connect two GPIO pins, set one to `PWMOutputDevice`, set it's value to something between 0 and 1. Then use the second GPIO pin as `SmoothedInputDevice` and read in the values,)

**Comment by lurch** [comment]
I guess this can be closed now?
