### ISSUE TITLE
Cannot import name LED

### ISSUE THREAD

**Issue by consolacion** [RPi-Distro/python-gpiozero#624]
Trying some of the simplest gpiozero examples like:

```python
from gpiozero import LED
from time import sleep

led = LED(17)

while True:
    led.on()
    sleep(1)
    led.off()
    sleep(1)
```

and

```python
from gpiozero import LED, Button
from signal import pause

led = LED(17)
button = Button(3)

button.when_pressed = led.on
button.when_released = led.off

pause()

```
But keep getting the "Cannot import name LED" error.
Using Raspian Stretch with python 2.7.
gpiozero lib is version 1.4.1

Have no idea what is wrong. Other 'can't import name XXXX' errors didnt really help me further.
Anyone any suggestions?

**Comment by bennuttall** [comment]
You have named your file `gpiozero.py` and the import line is trying to import LED from that file, not from the library.

You need to delete `gpiozero.py` (and if there's a `gpiozero.pyc` delete that too).

**Comment by consolacion** [comment]
You sir are either a mind reader or have secret access to my drive. Indeed that seems to be the issue. I presume that same issue  counts for any file name with gpiozero in it, even gpiozero_led.
thank you!!

**Comment by bennuttall** [comment]
Hehe I know, it's a common problem.

> I presume that same issue counts for any file name with gpiozero in it, even gpiozero_led.

No - only `gpiozero.py` will cause this error.

**Comment by consolacion** [comment]
Tnx again. Seems  a great and easy library

**Comment by bennuttall** [comment]
:+1:
