### ISSUE TITLE
Pinfactory for I2C Input or Output Extension

### ISSUE THREAD

**Issue by mgiaco** [RPi-Distro/python-gpiozero#625]
Hello,
I there a possibility to use external I2C Inputs and Outputs over the PinFactory mechanism. I cannot find anything about that. Is something already implemented or on the road map. If not I am willing to help and implement that.

cheers 
mathias

**Comment by bennuttall** [comment]
This is planned - see #199. It's been planned for a while but we are looking to start work on this soon.
