### ISSUE TITLE
Led flickering while using PWMLED

### ISSUE THREAD

**Issue by danielkalenda** [RPi-Distro/python-gpiozero#641]
I used gpiozero in order to dim an 24v led stripe.
However something appears to be wrong at this moment, or the software is meant to be used differently.
I used led = PWMLED(18) and turned the led.value = 0.2. 
At first it appeared to be working fine, however it started to flicker from time to time. 
Sometimes it started blinking wildly out of control after changing the value. 

after that i tried
gpio -g mode 18 pwm
gpio -g pwm 18 200

This worked without any issue, is anyone else having this issue? Or any idea how to fix it?

**Comment by bennuttall** [comment]
As @lurch said, you're likely using the default pin library RPi.GPIO as your back-end. This library uses software PWM, which isn't as reliable as hardware PWM used by wiringpi. You can, however, use pigpio as your back-end and you should get much better PWM control.

Try this:

1. Run `sudo pigpiod` to start the pigpio daemon
2. Run `export GPIOZERO_PIN_FACTORY=pigpio`
3. Type `python3` and try running your PWMLED code

For more info read up on PiGPIOFactory and changing the pin factory in the docs:
https://gpiozero.readthedocs.io/en/stable/api_pins.html#module-gpiozero.pins.pigpio
https://gpiozero.readthedocs.io/en/stable/api_pins.html#changing-the-pin-factory
