### ISSUE TITLE
It's possible to create a LEDBoard on no pins

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#643]
I would expect:

```python
leds = LEDBoard()
```

to raise an exception, but it doesn't. It just creates an empty `LEDBoard` object:

```python
<gpiozero.LEDBoard object closed>
```

We should bad init add tests for cases like this and make sure it shows an error similar to when mandatory `pin` arguments are not provided, e.g:

```python
>>> led = LED()
GPIOPinMissing: No pin given
>>> lights = TrafficLights()
GPIOPinMissing: red, amber, green pins must be provided
```

**Comment by lurch** [comment]
Did you mean "We should add bad init tests for..." :wink:

**Comment by bennuttall** [comment]
:)
