### ISSUE TITLE
rgbled.py example included int recipes.rst (Basic Recipes) does not work with Python 2

### ISSUE THREAD

**Issue by jdimpson** [RPi-Distro/python-gpiozero#645]
Hi! First, thanks for developing and maintaining this package.

[Line 27 of rgbled.py](https://github.com/RPi-Distro/python-gpiozero/blob/master/docs/examples/rgbled.py#L27) example code that is included in the Basic Recipes documentation does not work in python 2, while it does in python 3.  Under python 2 this division calculation always results in 0, so the blue LED never gets lit, while in python 3 it returns the intended floating point value.

Recommend either dividing by 100.0 to force a floating point context, or putting a comment that python 3 is required.

**Comment by bennuttall** [comment]
Thanks for letting us know. Now fixed, and will appear on the "latest" branch of the docs shortly, but not "stable" (the default) until the next release.
