### ISSUE TITLE
Support for other HW (e.g. Temp sensor SHT1x)

### ISSUE THREAD

**Issue by chasseurmic** [RPi-Distro/python-gpiozero#648]
Hello, 

I've been tinkering around with gpiozero for a couple of days now and I haven't found any indication of this in the docs: how can I extend the functionalities of the library to support other kind of hardware? How am I supposed to read the value of a PIN (let's say from a temp / hum sensor such as the SHT1x family)? Should I use a generic InputDevice and call .value() in itself?

Thank you for any suggestion on the best way to proceed.

**Comment by lurch** [comment]
I did a quick search, and found https://www.letscontrolit.com/wiki/index.php/SHT1X which says
> The SHT1x uses it's own protocol. Be aware: On first sight it looks like an I²C but it is not compatible to I²C.

so I don't think it'd be easy to add support for that to GpioZero. https://duckduckgo.com/?q=SHT1x+raspberry+pi should get you going in the right direction though :wink:
