### ISSUE TITLE
LineSensor - inverted output

### ISSUE THREAD

**Issue by martinohanlon** [RPi-Distro/python-gpiozero#652]
I am using this line sensor...  

https://www.aliexpress.com/item/Line-tracking-Sensor-For-robotic-and-car-DIY-Arduino-projects-Digital-Out/32654587628.html?spm=a2g0s.9042311.0.0.72924c4dZUXJvS

In summary - LineSensor.line_detected returns `True` when not on a line and `False` when on a line.

Its output is inverted to the LineSensor implemented in gpiozero. It is 'active' when the line is not detected and gpiozero offers no way of changing this. 

I need to be able to set pull_up=True on the SmoothInputDevice.

My current hack looks like this:

```python
left_sensor = LineSensor(17)
left_sensor._active_state = not left_sensor._active_state
left_sensor._inactive_state = not left_sensor._inactive_state
```

is having a pull_up on the LineSensor constructor the right implementation though? Is it really a pull up? or more of an `active_state`?

**Comment by bennuttall** [comment]
Addressed in PR #654
