### ISSUE TITLE
Can't Locate 'pinout' After Install 'python-gpiozero'

### ISSUE THREAD

**Issue by blogabe** [RPi-Distro/python-gpiozero#656]
I have an original RPi that I'm running with DietPi.  After installing python-gpiozero per the Instructions, I cannot execute or find the pinout command.

Is this an issue due to running on original RPi, DietPi, or something alltogether different?  Appreciate your help.

**Comment by bennuttall** [comment]
Sorry I didn't see this issue when you posted it.

I think the `pinout` tool is only installed when you install the Python 3 version of the package. We can't bundle it with both versions as they would overlap, so we chose the Python 3 version.

```bash
sudo apt install python3-gpiozero
```

will bring the `pinout` tool in. Can you confirm?

**Comment by blogabe** [comment]
Hi there.  Thanks.  I'm trying to remember if I tried that or not prior to posting, but can't recall.  I'll try it soon and will test it out. Thanks.

**Comment by blogabe** [comment]
Can confirm this works now.  Thanks so much @bennuttall

**Comment by bennuttall** [comment]
:+1:
