### ISSUE TITLE
Request to add support to play audio file

### ISSUE THREAD

**Issue by winkleink** [RPi-Distro/python-gpiozero#657]
For interactive projects it would be great to be able to play an audio file. wav/mp3/ogg. 
Maybe with volume control. 

Thinking for beginners it adds an alternative output to make learning more fun.

**Comment by SteveAmor** [comment]
@winkleink how do you see this from a command point of view?  Something like:

from gpiozero import PlayWAV, Button
from system import pause

mysound = PlayWAV("/home/pi/tada.wav")
button = Button(21)

button.when_pressed = mysound.on  # ```on``` is consistent with gpiozero but ```play``` may be better

pause()

**Comment by SteveAmor** [comment]
WAV files would be easier to handle as the system wav player ```aplay``` comes as standard with Stretch and Stretch Lite.  So we can make a system call to ```aplay```.  No way to adjust to volume with ```aplay``` though.  It would probably reside in other_devices.py ??

**Comment by winkleink** [comment]
That would work.
Thought process is to reduce the number of import statements a beginner has to use.

**Comment by bennuttall** [comment]
We wouldn't add this to gpiozero but instead recommend playing sounds with pygame:

```python
from gpiozero import Button
import pygame.mixer
from pygame.mixer import Sound
from signal import pause

pygame.mixer.init()

btn = Button(2)
drum = Sound("drum.wav")

btn.when_pressed = drum.play

pause()
```

One of the recipes in the docs includes a sound player for multiple sounds controlled by a series of buttons: https://gpiozero.readthedocs.io/en/stable/recipes.html#gpio-music-box
