### ISSUE TITLE
GPIOZero Button not working with tilt switch.  RPi.GPIO works

### ISSUE THREAD

**Issue by winkleink** [RPi-Distro/python-gpiozero#660]
I am using some single tilt switches (https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F111619897510)

The goal is to use them as a momentary switch when shaken as an input.
Attached screen shots for the 2 sets of code.

With GPIOZero it never prints "The button was pressed!!"
If I short the connection to simulate the button tilt sense connecting then the print statement is done.

**GPIOZero Code:**

```
from gpiozero import Button

button = Button(4)

while True:
    if button.is_pressed:
        print("The button was pressed!!")
```

**RPi.GPIO Code:**

```
import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BCM)
GPIO.setup(4, GPIO_IN,pull_up_down=GPIO.PUD_DOWN)

score = 0

while True:
    if GPIO.input(4):
        score = score+1
        sleep(0.05)
        print("Your score is: " + str(score))
        while GPIO.input(4)
            pass
```

![gpiozero-tilt](https://user-images.githubusercontent.com/6849504/42635736-c28b9276-85de-11e8-92dd-877f949396b8.png)
![rpi-gpio-tilt](https://user-images.githubusercontent.com/6849504/42635740-c5b76b5a-85de-11e8-89d4-35995e72dbd9.png)

**Comment by bennuttall** [comment]
In the RPi.GPIO code you are pulling down, but the default in gpiozero is pull-up. Instead use:

```python
button = Button(4, pull_up=False)
```

**Comment by winkleink** [comment]
That works.  Thanks.
