### ISSUE TITLE
Add reed sensor wrapper class

### ISSUE THREAD

**Issue by hansegucker** [RPi-Distro/python-gpiozero#662]
Is it possible to add a wrapper class for reed sensors (working like a button)?

Example:
```
reed = ReedSensor()
reed.is_closed = do_something
reed.is_open = do_another_thing
```

**Comment by lurch** [comment]
Why is just using the `Button` class directly not a suitable option? (since I guess a reed sensor is basically just a button that's 'pressed' by a magnet, instead of pressed by a finger? :man_shrugging: )

**Comment by hansegucker** [comment]
I know that's the same and I did it like @lurch and @bennuttall, but I tought that it could be better for beginners in Python to have a own class for that.
