### ISSUE TITLE
Escape sequence \* in triple quote block deprecated

### ISSUE THREAD

**Issue by ricksbt** [RPi-Distro/python-gpiozero#671]
Warning on a number of triple quote blocks

DeprecationWarning: invalid escape sequence \*
  """

Note that you only get this if Python is recompiling the .pyc files, it is usually hidden when running the tests.

**Comment by bennuttall** [comment]
PR #671 merged

**Comment by lurch** [comment]
I think you mean PR #673 merged? :wink:

**Comment by bennuttall** [comment]
:laughing: yes
