### ISSUE TITLE
pinout: command not found

### ISSUE THREAD

**Issue by a-x-** [RPi-Distro/python-gpiozero#705]
Operating system:  **Raspbian Stretch Lite**
Pi model: Pi **zero 1.3**
GPIO Zero version:  **1.4.1**
Pin factory used: RPiGPIO

i'm trying to use the `pinout` cli

I have an `/home/pi/.local/lib/python3.5/site-packages/gpiozerocli/pinout.py`

I just installed python3:
`sudo apt install python3 python3-pip`

and gpiozero:
`pip3 install gpiozero`

**Comment by lurch** [comment]
https://gpiozero.readthedocs.io/en/stable/installing.html suggests installing GpioZero on Raspbian using `apt`...

**Comment by a-x-** [comment]
okay...
