### ISSUE TITLE
equivalent of RPi.GPIO.cleanup()

### ISSUE THREAD

**Issue by matth-c3** [RPi-Distro/python-gpiozero#706]
Operating system: e.g. Raspbian Stretch
Pi model: e.g. Pi 3 Model B
GPIO Zero version: e.g. 1.4.1
Pin factory used: e.g. RPiGPIO
See http://rpf.io/gpzissue for information on how to find out these details

Hello, 

What is the equivalent of RPi.GPIO.cleanup() when using gpiozero ? 

thanks

**Comment by bennuttall** [comment]
Cleanup is called automatically at the end of the script.

In this example:

```python
from gpiozero import LED
from time import sleep

led = LED(2)

led.on()
sleep(5)
```

The LED comes on for 5 seconds, and then is cleaned up, and turned back off (the pin is returned to the state it was found at the start).

You can do it manually by running `led.close()` but this is unnecessary if your script ends naturally. If you `Ctrl + C` it the pin won't be cleaned up.
