### ISSUE TITLE
Traffic Lights recipe uses only a single LED?

### ISSUE THREAD

**Issue by DeeJay** [RPi-Distro/python-gpiozero#71]
re: https://github.com/RPi-Distro/python-gpiozero/blob/master/docs/recipes.md

from gpiozero import LED
from time import sleep

red = LED(2)
amber = LED(2)
green = LED(2)

Does that only control the LED associated with gpio2, or is there some 'magic' that I have not understood?

**Comment by bennuttall** [comment]
Sorry - it's just a stupid copy-paste mistake in the documentation. It should, of course, be:

```python
red = LED(2)
amber = LED(3)
green = LED(4)
```

I'll fix now.
