### ISSUE TITLE
pinout ASCII art for 3A+/3B+

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#721]
@waveform80 can you add PoE pins and things to the 3A+/3B+ boards in `pinout`?

**Comment by bennuttall** [comment]
This can be closed when docs-tidy-up is merged

**Comment by lurch** [comment]
For consistency, I wonder if it makes sense for _all_ the ASCII-art diagrams to use `{model:4s}`? Currently some use `{model:3s}` and some use `{model:4s}`.
