### ISSUE TITLE
Ensure every class's repr is tested

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#730]
It's possible for all tests to be passing but a device's repr fail, as I just found with `TonalBuzzer`.

I added a call to `repr(tb)` at the top of the first test for `TonalBuzzer` and since calling it raised an exception.

I know some tests actually inspect the contents of repr. Do we think this is necessary for all classes? Maybe. I think there should be at least a "test" that repr doesn't fall over.

@waveform80 @lurch thoughts?

**Comment by lurch** [comment]
I agree with @bennuttall - every class's `repr` should at least be callable (at any time) without causing an Exception, but I don't think there's any need to explicitly test the contents of each repr, since it's an "internal detail" and not part of the GpioZero API. All IMHO.

**Comment by bennuttall** [comment]
There's no harm in testing the implementation e.g. tonal buzzer's repr should now be `<TonalBuzzer playing tone A4>` but as I say, we should *at least* test that repr actually works.

**Comment by lurch** [comment]
> I don't think there's any need to explicitly test the contents of each repr

...although I guess that you could at least test that `repr()` returns a `str` with length > 1, and if you wanted to get fancy you could check it starts with `<gpiozero.`

**Comment by bennuttall** [comment]
That makes sense
