### ISSUE TITLE
Incorrect link in documentation 

### ISSUE THREAD

**Issue by jonwitts** [RPi-Distro/python-gpiozero#766]
On this page of of the documentation: https://gpiozero.readthedocs.io/en/stable/recipes.html#push-button-stop-motion the link to the "Push Button Stop Motion" RPi project is incorrect. It should go here: https://projects.raspberrypi.org/en/projects/push-button-stop-motion 

Thanks,
Jon

**Comment by lurch** [comment]
Oooh, well spotted! :+1: 

@bennuttall Should all the other `https://www.raspberrypi.org/learning/....` links also be updated to the new `https://projects.raspberrypi.org/en/projects/....` format? :man_shrugging:

**Comment by bennuttall** [comment]
Not a big deal as redirects are in place. We can update them but unless they're broken it doesn't really matter.

**Comment by bennuttall** [comment]
Fixed, thanks :+1:
