### ISSUE TITLE
pin property accessible?

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#8]
```python
led = LED(2)
led.on()  # it works
led.pin = 3
led.off()  # error
```

Users can do this. Should I care? @waveform80 

Alternatively, the `pin` property could be prefixed with an underscore.

**Comment by bennuttall** [comment]
It could be handy to read this value, but if people think they can write it, they may expect it to work. It won't because the `__init__` does the setup. I don't think it's worth making this work - but is it worth preventing it? If so, how?

**Comment by waveform80** [comment]
Easy enough to make pin a read only property - I'll bung together a PR in a
bit (might be an hour or so - just wrestling with mail servers at the mo!)

**Comment by bennuttall** [comment]
Great, thanks
