### ISSUE TITLE
Add "advanced" docs for generic classes

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#80]

**Comment by waveform80** [comment]
This is (partially) addressed in PR #101

**Comment by waveform80** [comment]
I'm going to call this complete for now; we've got docs on every base class and method (that matter - I'm happy leaving out the really weird stuff like the base metaclass), some pretty class hierarchy diagrams, and it's all wrapped up in its own chapter. Maybe in future we can add some recipes for the generics but that can be another ticket for another release.
