### ISSUE TITLE
Missing init param descriptions in documentation

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#82]
I added descriptions of initialisation options to the docs yesterday. Filled most of them in but I'm afraid I couldn't complete some of them. @waveform80 could you take a look and fill in the gaps where I've left `???` (and maybe check the sensor ones I've attempted to write).

Sorry/thanks

**Comment by waveform80** [comment]
This one's fully addressed in PR #101 as all the initializers are now documented from source code (and in each case I've gone through and ensured there are param descriptors for everything in the `__init__`)

**Comment by waveform80** [comment]
This one's also good to go.
