### ISSUE TITLE
Update Robot interface to account for recent Motor changes

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#85]
I just noticed the `Robot` class still contains references to `self._min_pwm` and so on. Looks like these should be removed/updated.

**Comment by waveform80** [comment]
Ah, this is fixed in the commit 8bdbac263000fb851f6183617f79f9742563fa62

**Comment by bennuttall** [comment]
Cool. Looks like I need to redo #84 to fix #81.
