### ISSUE TITLE
MCP300X argument ordering?

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#92]
It occurred to me recently that you're more likely / more often to set the `channel` than the `device` in `MCP3008` initialisation. Therefore, should the argument order be reversed? i.e.

```python
a = MCP3008(1)  # equivalent to MCP3008(channel=1)
```

For:

- Easier to address quickly
- Least significant bit first makes sense (or does it?)

Against:

- You can use named arguments anyway e.g. `channel=1`
- Most significant bit first makes sense (or does it?)

**Comment by waveform80** [comment]
Hmm ... good question! I'll have a think about that.

**Comment by bennuttall** [comment]
Like with many of these questions and suggestions, I'm sitting on the fence. I think we've made some good decisions by talking it through in issues.

**Comment by bennuttall** [comment]
Any thoughts?

**Comment by waveform80** [comment]
Not yet - but I'm still recovering from picademy :) I'll get on this tomorrow!

**Comment by lurch** [comment]
Whatever the outcome from this issue, it seems clear that the documentation for the MCP3008 needs tidying up - it talks about e.g. `wait_for_light()` ??

**Comment by waveform80** [comment]
Well, I completely failed to get on this 11 days ago (according to GitHub). Sorry - been busy with picademy and software carpentry obligations. Tomorrow, honest!

**Comment by bennuttall** [comment]
Ok decision is to go ahead and swap argument ordering

**Comment by bennuttall** [comment]
@waveform80 did I miss anything?

**Comment by bennuttall** [comment]
Technically the examples in the docs that use `MCP3008(channel=1)` are not wrong but could be changed to  `MCP3008(1)` but I think it's ok to leave it.

**Comment by waveform80** [comment]
Yeah, leave the docs as is - it makes things absolutely clear that you're talking about the channel and people can always figure out that it can be specified positionally.
